# Generated by Django 5.0.6 on 2024-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('market', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('item', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('currency', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
